name: Laravel

on:
  push:
    branches: ["master"]

jobs:
  job_1:
    name: Build Clinic Michelle App
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        with:
          clean: false
      - name: Copy .env
        env:
          ENV_PROD: ${{ secrets.ENV_PROD }}
        run: |
          rm -f .env
          touch .env
          echo "${ENV_PROD// /}" | base64 --decode > .env
      - name: Install Dependencies Backend
        run: composer install
      - name: Install Dependencies Frontend
        run: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          npm install
          npm run build
      - name: Clear Cache
        run: |
          php artisan cache:clear
          php artisan route:clear
          php artisan config:clear
      - name: Directory Permissions Backend
        run: echo N0hansen!z | sudo -S chmod -R 777 storage bootstrap/cache
