name: Laravel

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  job_1:
    name: Build Clinic Michelle App
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        with:
          clean: false
      - name: Copy .env
        run: cp .env.production .env
      - name: Install Dependencies Backend
        run: composer install
      - name: Install Dependencies Frontend
        run: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          npm install
          npm run build
      - name: Clear Cache
        run: |
          php artisan cache:clear
          php artisan route:clear
          php artisan config:clear
      - name: Directory Permissions Backend
        run: echo N0hansen!z | sudo -S chmod -R 777 storage bootstrap/cache
