name: Laravel

on:
  push:
    branches: ["master"]

jobs:
  job_1:
    name: Build Clinic Michelle App
    runs-on: self-hosted
    environment: production
    steps:
      - uses: actions/checkout@v2
        with:
          clean: false
      - name: Copy .env
        env:
          DOT_ENV: ${{ secrets.ENCRYPTED_DOT_ENV }}
        run: |
          rm -f .env
          touch .env
          echo "${DOT_ENV// /}" | base64 --decode > .env
      - name: Install Dependencies Backend
        run: composer install
      - name: Install Dependencies Frontend
        run: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          npm install
          npm run build
      - name: Clear Cache
        run: |
          php artisan cache:clear
          php artisan route:clear
          php artisan config:clear
      - name: Stop PM michelle
        run: pm2 stop michelle
      - name: Run Process Manager
        run: pm2 start ecosystem.config.js
      - name: Save PM
        run: pm2 save
      - name: Directory Permissions Backend
        run: echo ${{ secrets.DROPLET_PASS }} | sudo -S chmod -R 777 storage bootstrap/cache
